apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-deployment
  labels:
    app: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:20.04
        command: ["/bin/sh"]
        args: ["-c", "while true; do date; sleep 600;done"]
