apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reaper
rules:
- apiGroups:
  - ""
  resources:
  - 'namespaces'
  - 'pods'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
- apiGroups:
  - "apps"
  resources:
  - 'replicasets'
  - 'deployments'
  - 'statefulsets'
  - 'daemonsets'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
  - 'delete'
